AWSTemplateFormatVersion: '2010-09-09'
Description: RESTFull Users API
Globals:
  Function:
    Environment:
      Variables:
        ENVIRONMENT:
          Ref: ENVIRONMENT
        LOGLEVEL:
          Ref: LOGLEVEL
        REGION:
          Ref: REGIONNAME
        TABLE:
          Ref: TABLENAME
    Runtime: python3.7
    Timeout: 6
Parameters:
  ENVIRONMENT:
    Default: prod
    Description: Set the runtime environment
    Type: String
  LOGLEVEL:
    Default: INFO
    Description: Logger level
    Type: String
  REGIONNAME:
    Default: us-east-2
    Description: Default region for deployment.
    Type: String
  TABLENAME:
    Default: Users
    Description: The DynamoDB table for storing Users information.
    Type: String
Resources:
  DELETEUserFunction:
    Properties:
      CodeUri: s3://nicoglp-artifacts/b71c7699fb60d7bbc63a4640cd13836f
      Description: RESTFull API - DELETE Method to remove an Users entity
      Events:
        UsersPOST:
          Properties:
            Method: DELETE
            Path: /users/{id}
          Type: Api
      Handler: app.api_lambda.delete
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  GETUserFunction:
    Properties:
      CodeUri: s3://nicoglp-artifacts/32d9c61f0868d7e6fef979e06c6fd684
      Description: RESTFull API - GET Method to retrieve an Users entity
      Events:
        UsersPOST:
          Properties:
            Method: GET
            Path: /users/{id}
          Type: Api
      Handler: app.api_lambda.get
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  INGESTUserFunction:
    Events:
      CSVCreated:
        Properties:
          Bucket: gentem-bucket
        Type: S3
    Properties:
      CodeUri: s3://nicoglp-artifacts/533230a3dae9242a17fefff2a5181599
      Description: Lambda function that ingest new CSV files on bucket gentem-bucket
      Handler: app.users_ingestion.ingest_users
      Policies: AmazonS3FullAccess
    Type: AWS::Serverless::Function
  LISTUserFunction:
    Properties:
      CodeUri: s3://nicoglp-artifacts/a1a30f0a2bd532a8e40c2cff010944ea
      Description: RESTFull API - GET Method to retrieve list of Users
      Events:
        UsersPOST:
          Properties:
            Method: GET
            Path: /users
          Type: Api
      Handler: app.api_lambda.list
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  POSTUserFunction:
    Properties:
      CodeUri: s3://nicoglp-artifacts/894a4123fed3127633f215510320c14d
      Description: RESTFull API - POST Method to create a new Users entity
      Events:
        UsersPOST:
          Properties:
            Method: POST
            Path: /users
          Type: Api
      Handler: app.api_lambda.post
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  PUTUserFunction:
    Properties:
      CodeUri: s3://nicoglp-artifacts/89c939cde32c6f3c1c92b954b0181378
      Description: RESTFull API - PUT Method to update a complete Users entity
      Events:
        UsersPOST:
          Properties:
            Method: PUT
            Path: /users/{id}
          Type: Api
      Handler: app.api_lambda.put
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  UsersTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: email
        AttributeType: S
      KeySchema:
      - AttributeName: email
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        Ref: TABLENAME
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
