AWSTemplateFormatVersion: '2010-09-09'
Description: RESTFull Users API
Globals:
  Function:
    Environment:
      Variables:
        ENVIRONMENT:
          Ref: ENVIRONMENT
        INGEST_CSV_DELIMITER:
          Ref: INGESTCSVDELIMITER
        LOGLEVEL:
          Ref: LOGLEVEL
        REGION:
          Ref: REGIONNAME
        TABLE:
          Ref: TABLENAME
    Runtime: python3.7
    Timeout: 6
Parameters:
  ENVIRONMENT:
    Default: prod
    Description: Set the runtime environment
    Type: String
  INGESTCSVDELIMITER:
    Default: ;
    Description: CSV fields delimiter
    Type: String
  LOGLEVEL:
    Default: INFO
    Description: Logger level
    Type: String
  REGIONNAME:
    Default: us-east-2
    Description: Default region for deployment.
    Type: String
  TABLENAME:
    Default: Users
    Description: The DynamoDB table for storing Users information.
    Type: String
Resources:
  DELETEUserFunction:
    Properties:
      CodeUri: s3://nicoglp-artifacts/29d8e8d85a9b8e0d6192c844936e8243
      Description: RESTFull API - DELETE Method to remove an Users entity
      Events:
        UsersPOST:
          Properties:
            Method: DELETE
            Path: /users/{id}
          Type: Api
      Handler: app.api_lambda.delete
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  GETUserFunction:
    Properties:
      CodeUri: s3://nicoglp-artifacts/507832455bafa81e0f545f1cc21c1443
      Description: RESTFull API - GET Method to retrieve an Users entity
      Events:
        UsersPOST:
          Properties:
            Method: GET
            Path: /users/{id}
          Type: Api
      Handler: app.api_lambda.get
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  INGESTUserFunction:
    Events:
      CSVCreated:
        Properties:
          Bucket: gentem-bucket
        Type: S3
    Properties:
      CodeUri: s3://nicoglp-artifacts/b8792de53f7b7a0236d7936241f3daa9
      Description: Lambda function that ingest new CSV files on bucket gentem-bucket
      Handler: app.users_ingestion.ingest_users
      Policies:
      - AmazonS3FullAccess
      - AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  LISTUserFunction:
    Properties:
      CodeUri: s3://nicoglp-artifacts/e326405dc5e07fe537b8c9fb03f008f2
      Description: RESTFull API - GET Method to retrieve list of Users
      Events:
        UsersPOST:
          Properties:
            Method: GET
            Path: /users
          Type: Api
      Handler: app.api_lambda.list
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  POSTUserFunction:
    Properties:
      CodeUri: s3://nicoglp-artifacts/568d2b90322be4b0bf8da2863ca29ff1
      Description: RESTFull API - POST Method to create a new Users entity
      Events:
        UsersPOST:
          Properties:
            Method: POST
            Path: /users
          Type: Api
      Handler: app.api_lambda.post
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  PUTUserFunction:
    Properties:
      CodeUri: s3://nicoglp-artifacts/e027881e8b94867fe763b3e69ad9a33c
      Description: RESTFull API - PUT Method to update a complete Users entity
      Events:
        UsersPOST:
          Properties:
            Method: PUT
            Path: /users/{id}
          Type: Api
      Handler: app.api_lambda.put
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  UsersTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: email
        AttributeType: S
      KeySchema:
      - AttributeName: email
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        Ref: TABLENAME
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
