AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'RESTFull Users API'

Parameters:
  ENVIRONMENT:
    Type: String
    Description: Set the runtime environment
    Default: 'dev'
  TABLENAME:
    Type: String
    Description: The DynamoDB table for storing Users information.
    Default: 'Users'
  REGIONNAME:
    Type: String
    Description: Default region for deployment.
    Default: 'us-east-2'
  LOGLEVEL:
    Type: String
    Description: Logger level
    Default: 'DEBUG'

Globals:
  Function:
    Runtime: python3.7
    Timeout: 6
    Environment:
      Variables:
        ENVIRONMENT: !Ref ENVIRONMENT
        TABLE: !Ref TABLENAME
        REGION: !Ref REGIONNAME
        LOGLEVEL: !Ref LOGLEVEL

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TABLENAME
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  LISTUserFunction:
      Type: AWS::Serverless::Function
      Properties:
        Description: 'RESTFull API - GET Method to retrieve list of Users'
        CodeUri: .
        Handler: app.api_lambda.list
        Policies: AmazonDynamoDBFullAccess
        Events:
          UsersPOST:
            Type: Api
            Properties:
              Path: /users
              Method: GET

  POSTUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'RESTFull API - POST Method to create a new Users entity'
      CodeUri: .
      Handler: app.api_lambda.post
      Policies: AmazonDynamoDBFullAccess
      Events:
        UsersPOST:
          Type: Api
          Properties:
            Path: /users
            Method: POST

  GETUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'RESTFull API - GET Method to retrieve an Users entity'
      CodeUri: .
      Handler: app.api_lambda.get
      Policies: AmazonDynamoDBFullAccess
      Events:
        UsersPOST:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET

  PUTUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'RESTFull API - PUT Method to update a complete Users entity'
      CodeUri: .
      Handler: app.api_lambda.put
      Policies: AmazonDynamoDBFullAccess
      Events:
        UsersPOST:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: PUT

  DELETEUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'RESTFull API - DELETE Method to remove an Users entity'
      CodeUri: .
      Handler: app.api_lambda.delete
      Policies: AmazonDynamoDBFullAccess
      Events:
        UsersPOST:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: DELETE


